- hosts: all
  become: yes
  vars:
  roles:
    - geerlingguy.ntp
    - holms.fqdn
  tasks:
    - name: slurp cloud-init result.json
      slurp: src=/run/cloud-init/result.json
      failed_when: False
      register: result
    - name: set cloud-init facts
      set_fact: cloud_init="{{ ((result['content']|default()|b64decode) or '{ }') | from_json | combine(result) }}"
    - name: make ansible ssh user a passwordless sudoer if cloud-init absent
      copy:
        content: |
          # This file is managed by Ansible
          {{ ansible_ssh_user }} ALL=(ALL) NOPASSWD: ALL
        dest: /etc/sudoers.d/99-ansible_ssh_user
        mode: 0440
        validate: /usr/sbin/visudo -cf %s
      when: cloud_init.failed
  tags:
    - basic
